export const FETCH_SITE_SETTINGS = "FETCH_SITE_SETTINGS";
export const FETCH_SITE_SETTINGS_SUCCESS = "FETCH_SITE_SETTINGS_SUCCESS";
export const FETCH_SITE_SETTINGS_FAILED = "FETCH_SITE_SETTINGS_FAILED";

// HOME
export const FETCH_HOME_CONTENT = "FETCH_HOME_CONTENT";
export const FETCH_HOME_CONTENT_SUCCESS = "FETCH_HOME_CONTENT_SUCCESS";
export const FETCH_HOME_CONTENT_FAILED = "FETCH_HOME_CONTENT_FAILED";

//CONTACT US
// Contact Us and NEwsletter
export const SAVE_CONTACT_QUERY = "SAVE_CONTACT_QUERY";
export const SAVE_CONTACT_QUERY_SUCCESS = "SAVE_CONTACT_QUERY_SUCCESS";
export const SAVE_CONTACT_QUERY_FAILED = "SAVE_CONTACT_QUERY_FAILED";

export const SAVE_NEWSLETTER = "SAVE_NEWSLETTER";
export const SAVE_NEWSLETTER_SUCCESS = "SAVE_NEWSLETTER_SUCCESS";
export const SAVE_NEWSLETTER_FAILED = "SAVE_NEWSLETTER_FAILED";