export const FETCH_SITE_SETTINGS = "FETCH_SITE_SETTINGS";
export const FETCH_SITE_SETTINGS_SUCCESS = "FETCH_SITE_SETTINGS_SUCCESS";
export const FETCH_SITE_SETTINGS_FAILED = "FETCH_SITE_SETTINGS_FAILED";

// HOME
export const FETCH_HOME_CONTENT = "FETCH_HOME_CONTENT";
export const FETCH_HOME_CONTENT_SUCCESS = "FETCH_HOME_CONTENT_SUCCESS";
export const FETCH_HOME_CONTENT_FAILED = "FETCH_HOME_CONTENT_FAILED";

//CONTACT US
// Contact Us and NEwsletter
export const SAVE_CONTACT_QUERY = "SAVE_CONTACT_QUERY";
export const SAVE_CONTACT_QUERY_SUCCESS = "SAVE_CONTACT_QUERY_SUCCESS";
export const SAVE_CONTACT_QUERY_FAILED = "SAVE_CONTACT_QUERY_FAILED";

export const SAVE_NEWSLETTER = "SAVE_NEWSLETTER";
export const SAVE_NEWSLETTER_SUCCESS = "SAVE_NEWSLETTER_SUCCESS";
export const SAVE_NEWSLETTER_FAILED = "SAVE_NEWSLETTER_FAILED";

// AUTH
export const CREATE_ACCOUNT_MESSAGE = "CREATE_ACCOUNT_MESSAGE";
export const CREATE_ACCOUNT_MESSAGE_SUCCESS = "CREATE_ACCOUNT_MESSAGE_SUCCESS";
export const CREATE_ACCOUNT_MESSAGE_FAILED = "CREATE_ACCOUNT_MESSAGE_FAILED";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";
export const BACK_TO_SIGNUP = "BACK_TO_SIGNUP";

export const SIGN_IN_MESSAGE = "SIGN_IN_MESSAGE";
export const SIGN_IN_MESSAGE_SUCCESS = "SIGN_IN_MESSAGE_SUCCESS";
export const SIGN_IN_MESSAGE_FAILED = "SIGN_IN_MESSAGE_FAILED";

export const RESET_PASSWORD_LINK = "RESET_PASSWORD_LINK";
export const RESET_PASSWORD_LINK_SUCCESS = "RESET_PASSWORD_LINK_SUCCESS";
export const RESET_PASSWORD_LINK_FAILED = "RESET_PASSWORD_LINK_FAILED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

// Buyer Dashboard
export const FETCH_BUYER_DASHBOARD_DATA = "FETCH_BUYER_DASHBOARD_DATA";
export const FETCH_BUYER_DASHBOARD_DATA_SUCCESS = "FETCH_BUYER_DASHBOARD_DATA_SUCCESS";
export const FETCH_BUYER_DASHBOARD_DATA_FAILED = "FETCH_BUYER_DASHBOARD_DATA_FAILED";

export const FETCH_BUYER_ACCOUNT_SETTINGS = "FETCH_BUYER_ACCOUNT_SETTINGS";
export const FETCH_BUYER_ACCOUNT_SETTINGS_SUCCESS = "FETCH_BUYER_ACCOUNT_SETTINGS_SUCCESS";
export const FETCH_BUYER_ACCOUNT_SETTINGS_FAILED = "FETCH_BUYER_ACCOUNT_SETTINGS_FAILED";

export const SAVE_BUYER_ACCOUNT_SETTINGS = "SAVE_BUYER_ACCOUNT_SETTINGS";
export const SAVE_BUYER_ACCOUNT_SETTINGS_SUCCESS = "SAVE_BUYER_ACCOUNT_SETTINGS_SUCCESS";
export const SAVE_BUYER_ACCOUNT_SETTINGS_FAILED = "SAVE_BUYER_ACCOUNT_SETTINGS_FAILED";

export const CHANGE_BUYER_PASSWORD = "CHANGE_BUYER_PASSWORD";
export const CHANGE_BUYER_PASSWORD_SUCCESS = "CHANGE_BUYER_PASSWORD_SUCCESS";
export const CHANGE_BUYER_PASSWORD_FAILED = "CHANGE_BUYER_PASSWORD_FAILED";

// Professiuonal Dashboard
export const CREATE_PROFESSIONAL_PROFILE = "CREATE_PROFESSIONAL_PROFILE";
export const CREATE_PROFESSIONAL_PROFILE_SUCCESS = "CREATE_PROFESSIONAL_PROFILE_SUCCESS";
export const CREATE_PROFESSIONAL_PROFILE_FAILED = "CREATE_PROFESSIONAL_PROFILE_FAILED";

export const FETCH_PROFESSIONAL_DASHBOARD_DATA = "FETCH_PROFESSIONAL_DASHBOARD_DATA";
export const FETCH_PROFESSIONAL_DASHBOARD_DATA_SUCCESS = "FETCH_PROFESSIONAL_DASHBOARD_DATA_SUCCESS";
export const FETCH_PROFESSIONAL_DASHBOARD_DATA_FAILED = "FETCH_PROFESSIONAL_DASHBOARD_DATA_FAILED";

export const FETCH_PROFESSIONAL_ACCOUNT_SETTINGS = "FETCH_PROFESSIONAL_ACCOUNT_SETTINGS";
export const FETCH_PROFESSIONAL_ACCOUNT_SETTINGS_SUCCESS = "FETCH_PROFESSIONAL_ACCOUNT_SETTINGS_SUCCESS";
export const FETCH_PROFESSIONAL_ACCOUNT_SETTINGS_FAILED = "FETCH_PROFESSIONAL_ACCOUNT_SETTINGS_FAILED";

export const SAVE_PROFESSIONAL_ACCOUNT_SETTINGS = "SAVE_PROFESSIONAL_ACCOUNT_SETTINGS";
export const SAVE_PROFESSIONAL_ACCOUNT_SETTINGS_SUCCESS = "SAVE_PROFESSIONAL_ACCOUNT_SETTINGS_SUCCESS";
export const SAVE_PROFESSIONAL_ACCOUNT_SETTINGS_FAILED = "SAVE_PROFESSIONAL_ACCOUNT_SETTINGS_FAILED";

export const CHANGE_PROFESSIONAL_PASSWORD = "CHANGE_PROFESSIONAL_PASSWORD";
export const CHANGE_PROFESSIONAL_PASSWORD_SUCCESS = "CHANGE_PROFESSIONAL_PASSWORD_SUCCESS";
export const CHANGE_PROFESSIONAL_PASSWORD_FAILED = "CHANGE_PROFESSIONAL_PASSWORD_FAILED";

export const FETCH_SERVICES_DATA = "FETCH_SERVICES_DATA";
export const FETCH_SERVICES_DATA_SUCCESS = "FETCH_SERVICES_DATA_SUCCESS";
export const FETCH_SERVICES_DATA_FAILED = "FETCH_SERVICES_DATA_FAILED";


export const SAVE_SEARCH_DATA = "SAVE_SEARCH_DATA";
export const SAVE_SEARCH_DATA_SUCCESS = "SAVE_SEARCH_DATA_SUCCESS";
export const SAVE_SEARCH_DATA_FAILED = "SAVE_SEARCH_DATA_FAILED";

export const UPDATE_SERVICES_DATA = "UPDATE_SERVICES_DATA";
export const UPDATE_SERVICES_DATA_SUCCESS = "UPDATE_SERVICES_DATA_SUCCESS";
export const UPDATE_SERVICES_DATA_FAILED = "UPDATE_SERVICES_DATA_FAILED";

export const SAVE_BUSINESS_DATA = "SAVE_BUSINESS_DATA";
export const SAVE_BUSINESS_DATA_SUCCESS = "SAVE_BUSINESS_DATA_SUCCESS";
export const SAVE_BUSINESS_DATA_FAILED = "SAVE_BUSINESS_DATA_FAILED";

export const REQUEST_VERIFY_PHONE = "REQUEST_VERIFY_PHONE";
export const REQUEST_VERIFY_PHONE_SUCCESS = "REQUEST_VERIFY_PHONE_SUCCESS";
export const REQUEST_VERIFY_PHONE_FAILED = "REQUEST_VERIFY_PHONE_FAILED";

export const VERIFY_PHONE_NUMBER = "VERIFY_PHONE_NUMBER";
export const VERIFY_PHONE_NUMBER_SUCCESS = "VERIFY_PHONE_NUMBER_SUCCESS";
export const VERIFY_PHONE_NUMBER_FAILED = "VERIFY_PHONE_NUMBER_FAILED";

export const FETCH_MEM_SUBSCRIPTIONS = "FETCH_MEM_SUBSCRIPTIONS";
export const FETCH_MEM_SUBSCRIPTIONS_SUCCESS = "FETCH_MEM_SUBSCRIPTIONS_SUCCESS";
export const FETCH_MEM_SUBSCRIPTIONS_FAILED = "FETCH_MEM_SUBSCRIPTIONS_FAILED";

export const FETCH_BUYER_BOOKINGS = "FETCH_BUYER_BOOKINGS";
export const FETCH_BUYER_BOOKINGS_SUCCESS = "FETCH_BUYER_BOOKINGS_SUCCESS";
export const FETCH_BUYER_BOOKINGS_FAILED = "FETCH_BUYER_BOOKINGS_FAILED";

export const FETCH_BUYER_BOOKING_DETAILS = "FETCH_BUYER_BOOKING_DETAILS";
export const FETCH_BUYER_BOOKING_DETAILS_SUCCESS = "FETCH_BUYER_BOOKING_DETAILS_SUCCESS";
export const FETCH_BUYER_BOOKING_DETAILS_FAILED = "FETCH_BUYER_BOOKING_DETAILS_FAILED";

export const FETCH_REVIEW_PAGE_DATA = "FETCH_REVIEW_PAGE_DATA";
export const FETCH_REVIEW_PAGE_DATA_SUCCESS = "FETCH_REVIEW_PAGE_DATA_SUCCESS";
export const FETCH_REVIEW_PAGE_DATA_FAILED = "FETCH_REVIEW_PAGE_DATA_FAILED";

export const SAVE_REVIEW = "SAVE_REVIEW";
export const SAVE_REVIEW_SUCCESS = "SAVE_REVIEW_SUCCESS";
export const SAVE_REVIEW_FAILED = "SAVE_REVIEW_FAILED";

export const FETCH_PRO_NOTIFICATIONS = "FETCH_PRO_NOTIFICATIONS";
export const FETCH_PRO_NOTIFICATIONS_SUCCESS = "FETCH_PRO_NOTIFICATIONS_SUCCESS";
export const FETCH_PRO_NOTIFICATIONS_FAILED = "FETCH_PRO_NOTIFICATIONS_FAILED";

export const FETCH_BUYER_WISHLIST = "FETCH_BUYER_WISHLIST";
export const FETCH_BUYER_WISHLIST_SUCCESS = "FETCH_BUYER_WISHLIST_SUCCESS";
export const FETCH_BUYER_WISHLIST_FAILED = "FETCH_BUYER_WISHLIST_FAILED";

// CHAT

export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const FETCH_CONVERSATIONS_SUCCESS = "FETCH_CONVERSATIONS_SUCCESS";
export const FETCH_CONVERSATIONS_FAILED = "FETCH_CONVERSATIONS_FAILED";

export const START_CONVERSATION = "START_CONVERSATION";
export const START_CONVERSATION_SUCCESS = "START_CONVERSATION_SUCCESS";
export const START_CONVERSATION_FAILED = "START_CONVERSATION_FAILED";